### ISSUE TITLE
Pokemon Sun (and possibly moon) error.

### ISSUE THREAD

**Issue by Dkrogers1** [ZetaDesigns/Pokemon-Randomizing-GM9-Scripts#1]
I have the gamecartridge of pokemon sun obviously and I ran the script on godmode9.
After 20 excruciating minutes of waiting, and for the third time, I get this error.

Dumping failed.
Dumping the update failed.
Is there even an update?
( A to continue )

**Comment by Dkrogers1** [comment]
I will note that while this is a fresh project, I'm wholesomely relying on it to randomize my pokemon sun game.
Ever since I upgraded to bootstrap9 I'm unable to use most of the tutorials shown online, so.. yeah.

**Comment by ghost** [comment]
Please note that we are currently still finishing these scripts and need to possibly fix some of them.  Make sure you have the latest version of Sun/Moon installed.

**Comment by ZetaDesigns** [comment]
Since this is probably fixed with the new release, closing this.
