### ISSUE TITLE
Error when dumping (Pokemon Sun Cartridge dump)

### ISSUE THREAD

**Issue by Ichaeveil** [ZetaDesigns/Pokemon-Randomizing-GM9-Scripts#3]
When using the Cartridge Dump for Pokemon Sun, I get this error when I overwrite romfs

Dumping failed.
Copying romfs/exefs failed.

( <A> to continue)

When I press A:

0:/gm9/s...ts/Dump-Cartridge.gm9
Script execute failure
( <A> to continue)

**Comment by MechanicalDragon0687** [comment]
did you have a bit over 3gb of free space on the sd to dump the files?

**Comment by ZetaDesigns** [comment]
This is not an issue with the script and this issue tracker is not to be used for general assistance.
